config/routes.rb
EkBilling::Application.routes.draw do

  root :to => 'pages#splash'
  match '/about',                   :to => 'pages#about'
  match '/builder',                 :to => 'pages#builder'
  match '/contact',                 :to => 'pages#contact'
  match '/home',                    :to => 'pages#home'

  match '/login'                    => 'users#login',                   :as => :login
  match '/logout'                   => 'users#logout',                  :as => :logout

  match 'pages/signup'              => 'pages#signup',                  :as => :signup
  match 'pages/access_denied'       => 'pages#access_denied',           :as => :access_denied

  match 'invoices/confirm/:id'      => "invoices#confirm",              :as => :invoice_confirm
  match 'invoices/request_mail/:id' => "invoices#request_mail",         :as => :invoice_request
  match 'invoices/issued/:id'       => "invoices#issued",               :as => :invoice_issued
  match 'invoices/text/:id'         => "invoices#text",                 :as => :invoice_text
  match 'invoices/mailed/:id'       => "invoices#mailed",               :as => :invoice_mailed
  match 'invoices/reminder/:id'     => "invoices#reminder",             :as => :invoice_reminder
  match 'invoices/paid/:id'         => "invoices#paid",                 :as => :invoice_paid

  match 'autos/destroy/:id'         => "autos#destroy",                 :as => :delete_auto
  match 'categories/destroy/:id'    => "categories#destroy",            :as => :delete_category
  match 'customers/destroy/:id'     => "customers#destroy",             :as => :delete_customer
  match 'documents/destroy/:id'     => "documents#destroy",             :as => :delete_document
  match 'horses/destroy/:id'        => "horses#destroy",                :as => :delete_horse
  match 'invoices/destroy/:id'      => "invoices#destroy",              :as => :delete_invoice
  match 'items/destroy/:id'         => "items#destroy",                 :as => :delete_item
  match 'organizations/destroy/:id' => "organizations#destroy",         :as => :delete_organization
  match 'payments/destroy/:id'      => "payments#destroy",              :as => :delete_payment
  match 'users/destroy/:id'         => "users#destroy",                 :as => :delete_user

  match 'customs/sample'            => "customs#sample",                :as => :invoice_sample

  match 'users/create_customer'     => "users#customer_acct_from_form", :as => :customer_from_form
  match 'users/create_manager'      => "users#manager_acct_from_form",  :as => :manager_from_form
  match 'users/new_customer/:id'    => "users#create_customer_account", :as => :new_customer_account
  match 'customers/validate/:id'    => "customers#validate_customer",   :as => :validate_customer
  match 'customers/update'          => "customers#update_info",         :as => :update_customer

  match 'payments/authorize/:id'    => "payments#authorize",            :as => :authorize
  match 'payments/creditcard/:id'   => "payments#creditcard",           :as => :creditcard
  match 'payments/relay_response'   => "payments#relay_response",       :as => :relay_response
  match 'payments/receipt/:id'      => "payments#receipt",              :as => :payment_receipt
  match 'payments/error'            => "payments#error",                :as => :payment_error

  match 'android/getAllCustomers', :to => "android#get_all_customers"

  resources :autos
  resources :categories
  resources :customers
  resources :customs
  resources :documents
  resources :horses
  resources :invoices
  resources :items
  resources :organizations
  resources :payments
  resources :users

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  belongs_to  :organization
  belongs_to  :customer
  has_many    :items,    :order => "category_id asc, description asc"
  has_many    :payments, :order => "date asc"
  has_many    :statuses, :order => "status_code asc"

  validates :name,            :presence => true, :length => { :maximum => 250 }
  validates :start_date,      :presence => true
  validates :end_date,        :presence => true
  validates :issued_date,     :presence => true
  validates :due_date,        :presence => true
  validates :amount,          :presence => true, :format => { :with => /^[0-9]*(\.[0-9]{1,2})?$|^[0-9]{1,3}(,[0-9]{3})*(\.[0-9]{1,2})?$/ }
  validates :notes,           :length => { :maximum => 250 }
  validates :organization_id, :presence => true, :numericality => true
  validates :customer_id,     :presence => true, :numericality => true

  def Invoice.update_status(invoice_id, status)
    @invoice = Invoice.find(invoice_id)
    @status = Status.new
    @status.invoice_id = invoice_id
    @status.status = status
    status_code = 0
    if status == "Opened"
      status_code = 1
    elsif status == "Emailed" || status == "Mailed"
      status_code = 2
    elsif status == "Confirmed"
      status_code = 3
    elsif status == "Mail Requested"
      status_code = 4
    elsif status == "Mailed (Secondary)"
      status_code = 5
    elsif status == "Partially Paid"
      status_code = 6
    elsif status == "Reminded"
      status_code = 7
    elsif status == "Paid"
      status_code = 8
    end
    @status.status_code = status_code
    @status.created_at = Date.today.strftime("%Y-%m-%d %H:%M:%S")
    @status.updated_at = Date.today.strftime("%Y-%m-%d %H:%M:%S")
    if @status.save
      @invoice.update_attribute("status_code", status_code)
      @invoice.update_attribute("status", status)
      true
    else
      false
    end
  end

end

app/controllers/invoices_controller.rb
include ActionView::Helpers::NumberHelper

class InvoicesController < ApplicationController

  before_filter :login_required, :except => [ :request_mail ] #, :except => [ :confirm, :request_mail ]
  before_filter :manager_required, :except => [ :index, :show, :confirm, :request_mail ]

  # GET /invoices
  def index
    if session[:user][:access] == "customer"
      @invoices = Invoice.find_all_by_customer_id(session[:user][:customer_id])
    else
      # pay-attention invoices
      # - invoices to be mailed ("Mail Requested" or ("Opened" and @customer.delivery_method == "Mail"))
      # - invoices past due ("Emailed", "Mailed", "Confirmed", "Mailed (Secondary)", "Partially Paid", "Reminded" where due_date < now)
      pastdue_status_codes = [1, 2, 3, 4, 5, 6, 7]
      @attention_invoices = Invoice.find_all_by_organization_id(session[:user][:organization_id],
                                                                :order => 'end_date desc',
                                                                :conditions => [ "status_code = '4'
                                                                                  or (status_code in (?)
                                                                                  and due_date < ?)",
                                                                                  pastdue_status_codes, Date.today ])

      # open invoices
      # - "Opened", "Emailed", "Mailed", "Confirmed", "Mailed (Secondary)", "Reminded" where due_date > now
      # @opened_invoices = Invoice.all(:conditions => [ "statuses.status = ?" ])
      # @open_invoices = Invoice.where([ "status in ?" ], [ "Opened", "Emailed", "Mailed", "Confirmed",
      #                                  "Mailed (Secondary)", "Reminded" ]).and.where([ "due_date < " ], Time.now)
      open_status_codes = [1, 2, 3, 4, 5, 6, 7]
      @open_invoices = Invoice.find_all_by_organization_id(session[:user][:organization_id],
                                                           :order => 'end_date desc',
                                                           :conditions => [ "status_code in (?)
                                                                             and due_date >= ?",
                                                                             open_status_codes, Date.today ])

      # closed invoices
      # - "Paid"
      closed_status_codes = [8]
      @closed_invoices = Invoice.find_all_by_organization_id(session[:user][:organization_id],
                                                            :order => 'end_date desc',
                                                            :conditions => [ "status_code in (?)",
                                                                              closed_status_codes ])
    end
  end

  # GET /invoices/1
  def show
    @invoice = Invoice.find(params[:id])

    # check for any warnings (unconfirmed for X days, etc.)
    @status = Status.find_by_invoice_id(@invoice.id, :order => "status_code desc", :limit => 1)
    if @status.status == "Emailed"
      # time_diff_components = Time.diff(Time.now, @status.created_at)
      # if time_diff_components[:day] > 1
      #   @warning = "You emailed this invoice " + time_diff_components[:day].to_s + " ago, and it has not been confirmed."
      # end
    elsif @status.status == "Mail Requested"
      @warning = "This customer has requested a hard copy of this invoice to be mailed."
    elsif @invoice.due_date < Date.today && @invoice.status_code < 8
      @warning = "This invoice is past due."
    end

    @pastdue_items = []
    if @invoice.status_code < 8
      index = 0
      invoices = Invoice.find_all_by_customer_id(@invoice.customer_id)
      invoices.each do |invoice|
        if invoice.status_code < 8 && invoice.id != @invoice.id
          items = Item.find_all_by_invoice_id(invoice.id)
          items.each do |item|
            # only include items that are not denoted as past due on another invoice
            if item.category_id != 14 && invoice.end_date < @invoice.start_date
              @pastdue_items[index] = item.category.name + " - " + item.description + " (" + invoice.name + ")"
              index += 1
            end
          end
        end
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.pdf {
        render :layout => false
      }
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.organization_id = session[:user][:organization_id]
    @invoice.customer_id = params[:customer]

    if @invoice.customer_id.blank?
      @customers = Customer.find_all_by_organization_id(@invoice.organization_id)
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  def create
    @invoice = Invoice.new(params[:invoice])
    # default invoice amount = 0
    @invoice.amount = 0
    #@invoice.status_code = 1
    #@invoice.status = "Opened"

    if @invoice.save
      Invoice.update_status(@invoice.id, "Opened")
      redirect_to(@invoice, :notice => 'Invoice was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /invoices/1
  def update
    @invoice = Invoice.find(params[:id])

    if @invoice.update_attributes(params[:invoice])
      redirect_to(@invoice, :notice => 'Invoice was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /invoices/1
  def destroy
    @invoice = Invoice.find(params[:id])
    if @invoice.destroy
      redirect_to(invoices_url, :notice => 'Invoice was successfully deleted.')
    end
  end

  def text
    @invoice = Invoice.find(params[:id])
    if @invoice.nil? == false
      @customer = Customer.find(@invoice.customer_id)
      if @customer.cell.blank? == false
        @account_sid = 'ACca351063436f41d4b1357d3e2efc7bb8'
        @account_token = '2428ac438afe38001c955ac0d4b713c0'
        @client = Twilio::REST::Client.new(@account_sid, @account_token)
        @client.account.sms.messages.create(
            :from => '(415) 599-2671',
            :to   => '(717) 658-4502', # @customer.cell,
            :body => "Just a reminder from " + @invoice.organization.name + " that your invoice is due on " + @invoice.due_date.strftime("%B %e, %Y") + ". Thank you!"
        )
        success = Invoice.update_status(@invoice.id, "Reminded")
        if success == true
          redirect_to(@invoice, :notice => "Text message reminder was successfully sent.")
        else
          redirect_to(@invoice, :notice => "Something went wrong! Text message reminder was NOT successfully sent.")
        end
      else
        redirect_to(@invoice, :notice => "Something went wrong! Text message reminder was NOT successfully sent.")
      end
    end
  end

  def issued
    @invoice = Invoice.find(params[:id])
    if @invoice.nil? == false
      @customer = Customer.find_by_id(@invoice.customer_id)
      if @customer.nil? == false
        email =  "elysedougherty@gmail.com" #@customer.email
        if email.blank? == false
          # Send email to @email
          pdf = Prawn::Document.new()
          pdf = build_pdf(pdf, @invoice)
          pdf.render_file("#{Rails.root}/public/files/pdfs/issued/" + @invoice.id.to_s + ".pdf")
          InvoiceMailer.invoice_issued(@invoice).deliver
          success = Invoice.update_status(@invoice.id, "Emailed")
          if success == true
            redirect_to(@invoice, :notice => "Invoice email was successfully sent.")
          else
            redirect_to(@invoice, :notice => "Something went wrong! Email was NOT successfully sent.")
          end
        else
          redirect_to(@invoice, :notice => "Something went wrong! Email was NOT successfully sent.")
        end
      else
         redirect_to(@invoice, :notice => "Something went wrong! Email was NOT successfully sent.")
      end
    end
  end

  def confirm
    # Decrypt encrypted id from params
    #@param = params[:id]
    #cipher = Gibberish::AES.new("snoopyandlowerhopewellfarm")
    #@decrypted = cipher.dec(@param) # @param
    #@invoice = Invoice.find_by_id(@decrypted)
    @invoice = Invoice.find(params[:id])
    #@status = Status.find_by_invoice_id(@invoice.id, :order => "status_code desc", :limit => 1)
    success = Invoice.update_status(@invoice.id, "Confirmed")
    if success == true
      redirect_to(@invoice, :notice => "Invoice was confirmed successfully. Thank you in advance for your prompt payment!")
    else
      redirect_to(@invoice, :notice => "Something went wrong! Invoice was NOT successfully confirmed.")
    end
  end

  def request_mail
    # Decrypt encrypted id from params
    @param = params[:id]
    cipher = Gibberish::AES.new("snoopyandlowerhopewellfarm")
    @decrypted = cipher.dec(@param) # @param
    @invoice = Invoice.find(@decrypted)

    #@invoice = Invoice.find(params[:id])
    success = Invoice.update_status(@invoice.id, "Mail Requested")
    if success == true
      if session[:user]
        redirect_to(@invoice, :notice => "Your request was submitted successfully. A copy of this invoice will be on its way to you soon!")
      else
        @notice = "Your request was submitted successfully. A copy of this invoice will be on its way to you soon!"
        render 'request_mail'
      end
    else
      if session[:user]
        redirect_to(@invoice, :notice => "Something went wrong! Your request was NOT submitted successfully.")
      else
        @notice = ""
        render 'request_mail'
      end
    end
  end

  def reminder
    @invoice = Invoice.find(params[:id])
    InvoiceMailer.invoice_reminder(@invoice).deliver
    success = Invoice.update_status(@invoice.id, "Reminded")
    if success == true
      redirect_to(@invoice, :notice => "Reminder email was successfully sent.")
    else
      redirect_to(@invoice, :notice => "Something went wrong! Reminder email was NOT successfully sent.")
    end
  end

  def mailed

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :issued_date %>
    <%= f.date_select :issued_date %>
  </div>
  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <% if @invoice.customer_id.blank? %>
    <%= f.label :customer_id, "Customer" %>
    <% if @customers.empty? == false %>
        <%= select("invoice", "customer_id", @customers.collect { |p| [ p.last_name + ", " + p.first_name, p.id ] }) %>
    <% else %>
        You can't create an invoice without any customers. <%= link_to 'Add a customer now.', new_customer_path %>
    <% end %>
  <% else %>
    <%= hidden_field("invoice", "customer_id", :value => @invoice.customer_id) %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

  <%= hidden_field("invoice", "organization_id", :value => @invoice.organization_id) %>
<% end %>

app/views/invoices/confirm.html.erb
<div class="list">

<h1 class="title"><%= @invoice.name %></h1>

<p id="notice"><%= @notice %></p>

<div class="field">
    <label style="clear: left">Status</label>
    <%= @invoice.status %>
</div>

<div class="field">
    <label style="clear: left">Start date</label>
    <%= @invoice.start_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">End date</label>
    <%= @invoice.end_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">Issued date</label>
    <%= @invoice.issued_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">Due date</label>
    <%= @invoice.due_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">Amount</label>
    <%= number_to_currency(@invoice.amount) %>
</div>

<div class="field" style="padding-bottom: 20px">
    <label style="clear: left">Notes</label>
    <% if @invoice.notes.blank? == false %>
        <%= @invoice.notes %>
    <% else %>
        No notes have been entered
    <% end %>
</div>

</div>

app/views/invoices/edit.html.erb
<div class="breadcrumb">
  << <%= link_to 'INVOICES', invoices_path %>
  << <%= link_to @invoice.customer.last_name.upcase!, @invoice.customer %>
  << <%= link_to 'DETAILS', @invoice %>
</div>

<div class="list">

<h1 class="title"><%= @invoice.name %></h1>

<p class="notice"><%= notice %></p>
  
<%= render 'form' %>

</div>

app/views/invoices/index.html.erb
<div class="list">

<h1 class="title">Invoices</h1>
  
<p class="notice"><%= notice %></p>

<% if session[:user][:access] == "admin" %>

<% elsif session[:user][:access] == "manager" %>
    <% if session[:user][:organization_id] %>
        <%= link_to 'Add a new invoice', new_invoice_path, :class => "add_link" %>

        <div class="sub">
            <h2 class="sub_title" style="color: red">Pay Attention Invoices</h2>
            <% if @attention_invoices.empty? == false %>
                <table class="margin_above">
                <% @attention_invoices.each do |invoice| %>
                  <tr>
                    <td><%= link_to invoice.name, invoice %></td>
                    <td><%= invoice.customer.last_name %>, <%= invoice.customer.first_name %></td>
                    <% if invoice.status_code == 4 %>
                        <td class="attention"><%= invoice.status %></td>
                    <% else %>
                        <td><%= invoice.status %></td>
                    <% end %>
                    <% if invoice.due_date < Date.today %>
                        <td class="attention">Due <%= invoice.due_date.strftime("%B %e, %Y") %></td>
                    <% else %>
                        <td>Due <%= invoice.due_date.strftime("%B %e, %Y") %></td>
                    <% end %>
                    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this invoice?', '<%= delete_invoice_path(invoice) %>')">Remove</a></td>
                  </tr>
                <% end %>
            </table>
            <% else %>
                <p class="currently_no">There are currently no invoices requiring immediate attention.</p>
            <% end %>
        </div>

        <div class="sub">
            <h2 class="sub_title" style="color: #006600">Open Invoices</h2>
            <% if @open_invoices.empty? == false %>
                <table class="margin_above">
                <% @open_invoices.each do |invoice| %>
                  <tr>
                    <td><%= link_to invoice.name, invoice %></td>
                    <td><%= invoice.customer.last_name %>, <%= invoice.customer.first_name %></td>
                    <td><%= invoice.status %></td>
                    <td>Due <%= invoice.due_date.strftime("%B %e, %Y") %></td>
                    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this invoice?', '<%= delete_invoice_path(invoice) %>')">Remove</a></td>
                  </tr>
                <% end %>
            </table>
            <% else %>
                <p class="currently_no">There are currently no open invoices.</p>
            <% end %>
        </div>

        <div class="sub">
            <h2 class="sub_title" style="color: #000000">Closed Invoices</h2>
            <% if @closed_invoices.empty? == false %>
                <table class="margin_above">
                <% @closed_invoices.each do |invoice| %>
                  <tr>
                    <td><%= link_to invoice.name, invoice %></td>
                    <td><%= invoice.customer.last_name %>, <%= invoice.customer.first_name %></td>
                    <td>Due <%= invoice.due_date.strftime("%B %e, %Y") %></td>
                    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this invoice?', '<%= delete_invoice_path(invoice) %>')">Remove</a></td>
                  </tr>
                <% end %>
            </table>
            <% else %>
                <p class="currently_no">There are currently no closed invoices.</p>
            <% end %>
        </div>
    <% else %>
        <p class="currently_no">You can't start adding invoices until you get your barn information entered. <%= link_to 'Click here', new_organization_path %> to do that now.</p>
    <% end %>
<% elsif session[:user][:access] == "customer" %>
    <% if @invoices.empty? == false %>
        <table>
            <% @invoices.each do |invoice| %>
                <tr>
                  <td><%= link_to invoice.name, invoice %></td>
                  <td><%= invoice.status %></td>
                  <% if invoice.due_date < Date.today %>
                    <td class="attention"><%= invoice.due_date.strftime("%B %e, %Y") %></td>
                  <% else %>
                    <td><%= invoice.due_date.strftime("%B %e, %Y") %></td>
                  <% end %>
                </tr>
            <% end %>
        </table>
    <% else %>
      <p class="currently_no">There are currently no invoices entered for you. Talk to your barn manager and find out what's up!</p>
    <% end %>
<% end %>

</div>

app/views/invoices/new.html.erb
<div class="breadcrumb">
  <% if @invoice.customer.nil? %>
    << <%= link_to 'INVOICES', invoices_path %>
  <% else %>
    << <%= link_to 'INVOICES', invoices_path %> << <%= link_to @invoice.customer.last_name.upcase!, @invoice.customer %>
  <% end %>
</div>

<div class="list">

<h1 class="title">Invoices</h1>

<p class="notice"><%= notice %></p>
  
<%= render 'form' %>

</div>

app/views/invoices/request_mail.html.erb
<div class="list">

<h1 class="title"><%= @invoice.name %></h1>

<p id="notice"><%= @notice %></p>

<div class="field">
    <label style="clear: left">Status</label>
    <%= @invoice.status %>
</div>

<div class="field">
    <label style="clear: left">Start date</label>
    <%= @invoice.start_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">End date</label>
    <%= @invoice.end_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">Issued date</label>
    <%= @invoice.issued_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">Due date</label>
    <%= @invoice.due_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
    <label style="clear: left">Amount</label>
    <%= number_to_currency(@invoice.amount) %>
</div>

<div class="field" style="padding-bottom: 20px">
    <label style="clear: left">Notes</label>
    <% if @invoice.notes.blank? == false %>
        <%= @invoice.notes %>
    <% else %>
        No notes have been entered
    <% end %>
</div>

</div>

app/views/invoices/show.html.erb
<% if session[:user][:access] != "customer" %>
    <div class="breadcrumb">
        << <%= link_to 'INVOICES', invoices_path %> << <%= link_to @invoice.customer.last_name.upcase!, @invoice.customer %>
    </div>
<% end %>

<div class="list">

<h1 class="title"><%= @invoice.name %></h1>

<p id="notice"><%= notice %></p>

<% if session[:user][:access] == "manager" %>
    <%= link_to 'Email this invoice', invoice_issued_path(:invoice => @invoice), :class => "link_button" %>

    <div class="field" style="padding-top: 20px">
        <label style="clear: left">Status</label>
        <%= @invoice.status %>
    </div>
<% else %>
    <div class="field">
        <label style="clear: left">Status</label>
        <%= @invoice.status %>
    </div>
<% end %>

<div class="field">
<label style="clear: left">Start date</label>
<%= @invoice.start_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
<label style="clear: left">End date</label>
<%= @invoice.end_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
<label style="clear: left">Issued date</label>
<%= @invoice.issued_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
<label style="clear: left">Due date</label>
<%= @invoice.due_date.strftime("%B %e, %Y") %>
</div>

<div class="field">
<label style="clear: left">Amount</label>
<%= number_to_currency(@invoice.amount) %>
</div>

<div class="field" style="padding-bottom: 20px">
    <label style="clear: left">Notes</label>
    <% if @invoice.notes.blank? == false %>
        <%= @invoice.notes %>
    <% else %>
        No notes have been entered.
    <% end %>
</div>

    <%= link_to 'Download PDF', invoice_path(@invoice, :format => :pdf), :class => 'link_button' %>

    <% if session[:user][:access] == "manager" %>
        <%= link_to 'Edit details', edit_invoice_path(@invoice), :class => "link_button" %>
        <a href="#" onclick="confirm('Are you sure you want to delete this invoice?', '<%= delete_invoice_path(@invoice) %>')" class="link_button">Remove</a>
    <% end %>

    <% if session[:user][:access] == "customer" %>
        <%= link_to 'Request hard copy', invoice_request_path(@invoice), :class => "link_button" %>
    <% end %>

  <div class="sub">
    <h2 class="sub_title">Items</h2>
    <% if session[:user][:access] == "manager" %>
        <%= link_to 'Add a new item', new_item_path(:invoice => @invoice.id), :class => "add_link" %>
    <% end %>

    <% if @invoice.items.empty? == false %>
        <table class="margin_above">
          <% @invoice.items.each do |item| %>
            <tr>
                <td><%= item.category.name %></td>
                <td><%= item.description %></td>
                <% if item.horse.nil? == false %>
                    <td><%= item.horse.barn_name %></td>
                <% else %>
                    <td>No horse associated</td>
                <% end %>
                <td><%= number_to_currency(item.amount) %></td>
                <% if session[:user][:access] == "manager" %>
                    <td><%= link_to 'Edit', edit_item_path(item) %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this item?', '<%= delete_item_path(item) %>')">Remove</a></td>
                <% end %>
            </tr>
          <% end %>
        </table>
    <% else %>
        <p class="currently_no">This invoice currently has no items.</p>
    <% end %>
  </div>

  <div class="sub">
    <h2 class="sub_title">Payments</h2>
    <% if session[:user][:access] == "manager" %>
        <%= link_to 'Add a new payment', new_payment_path(:invoice => @invoice.id), :class => "add_link" %>
    <% elsif session[:user][:access] == "customer" %>
        <%= link_to 'Make a payment', creditcard_path(@invoice), :class => "add_link" %>
    <% end %>

    <% if @invoice.payments.empty? == false %>
        <table class="margin_above">
          <% @invoice.payments.each do |payment| %>
            <tr>
                <td><%= payment.payment_type %></td>
                <td><%= payment.date.strftime("%B %e, %Y") %></td>
                <td><%= payment.notes %></td>
                <td><%= number_to_currency(payment.amount) %></td>
                <td><%= link_to 'Receipt (PDF)', payment_receipt_path(payment, :format => :pdf) %></td>
                <% if session[:user][:access] == "manager" %>
                    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this payment?', '<%= delete_payment_path(payment) %>')">Remove</a></td>
                <% end %>
            </tr>
          <% end %>
        </table>
    <% else %>
        <p class="currently_no">This invoice currently has no payments.</p>
    <% end %>
  </div>

</div>