config/routes.rb
EkBilling::Application.routes.draw do

  root :to => 'pages#splash'
  match '/about',                   :to => 'pages#about'
  match '/builder',                 :to => 'pages#builder'
  match '/contact',                 :to => 'pages#contact'
  match '/home',                    :to => 'pages#home'

  match '/login'                    => 'users#login',                   :as => :login
  match '/logout'                   => 'users#logout',                  :as => :logout

  match 'pages/signup'              => 'pages#signup',                  :as => :signup
  match 'pages/access_denied'       => 'pages#access_denied',           :as => :access_denied

  match 'invoices/confirm/:id'      => "invoices#confirm",              :as => :invoice_confirm
  match 'invoices/request_mail/:id' => "invoices#request_mail",         :as => :invoice_request
  match 'invoices/issued/:id'       => "invoices#issued",               :as => :invoice_issued
  match 'invoices/text/:id'         => "invoices#text",                 :as => :invoice_text
  match 'invoices/mailed/:id'       => "invoices#mailed",               :as => :invoice_mailed
  match 'invoices/reminder/:id'     => "invoices#reminder",             :as => :invoice_reminder
  match 'invoices/paid/:id'         => "invoices#paid",                 :as => :invoice_paid

  match 'autos/destroy/:id'         => "autos#destroy",                 :as => :delete_auto
  match 'categories/destroy/:id'    => "categories#destroy",            :as => :delete_category
  match 'customers/destroy/:id'     => "customers#destroy",             :as => :delete_customer
  match 'documents/destroy/:id'     => "documents#destroy",             :as => :delete_document
  match 'horses/destroy/:id'        => "horses#destroy",                :as => :delete_horse
  match 'invoices/destroy/:id'      => "invoices#destroy",              :as => :delete_invoice
  match 'items/destroy/:id'         => "items#destroy",                 :as => :delete_item
  match 'organizations/destroy/:id' => "organizations#destroy",         :as => :delete_organization
  match 'payments/destroy/:id'      => "payments#destroy",              :as => :delete_payment
  match 'users/destroy/:id'         => "users#destroy",                 :as => :delete_user

  match 'customs/sample'            => "customs#sample",                :as => :invoice_sample

  match 'users/create_customer'     => "users#customer_acct_from_form", :as => :customer_from_form
  match 'users/create_manager'      => "users#manager_acct_from_form",  :as => :manager_from_form
  match 'users/new_customer/:id'    => "users#create_customer_account", :as => :new_customer_account
  match 'customers/validate/:id'    => "customers#validate_customer",   :as => :validate_customer
  match 'customers/update'          => "customers#update_info",         :as => :update_customer

  match 'payments/authorize/:id'    => "payments#authorize",            :as => :authorize
  match 'payments/creditcard/:id'   => "payments#creditcard",           :as => :creditcard
  match 'payments/relay_response'   => "payments#relay_response",       :as => :relay_response
  match 'payments/receipt/:id'      => "payments#receipt",              :as => :payment_receipt
  match 'payments/error'            => "payments#error",                :as => :payment_error

  match 'android/getAllCustomers', :to => "android#get_all_customers"

  resources :autos
  resources :categories
  resources :customers
  resources :customs
  resources :documents
  resources :horses
  resources :invoices
  resources :items
  resources :organizations
  resources :payments
  resources :users

end

app/models/document.rb
class Document < ActiveRecord::Base

  belongs_to :organization
  belongs_to  :customer
  belongs_to  :horse

  validates :description,     :presence => true, :length => { :maximum => 250 }
  validates :notes,           :length => { :maximum => 250 }
  validates :extension,       :inclusion => { :in => %w(pdf jpg jpeg gif png bmp), :message => "should be of type .jpg, .jpeg, .gif, .png, .bmp or .pdf." }
  validates :organization_id, :presence => true, :numericality => true
  validates :customer_id,     :numericality => true, :if => :customer?
  validates :horse_id,        :numericality => true, :if => :horse?

  def customer?()
    if self.customer_id.blank? == false
      true
    else
      false
    end
  end

  def horse?()
    if self.horse_id.blank? == false
      true
    else
      false
    end
  end

  # Root directory of the photo public/photos
  PHOTO_STORE = "#{Rails.root}/public/files/documents/"

  def self.save_image(id, ext, data)
    if data
      filename_ext = id.to_s + "." + ext
      filename = File.join PHOTO_STORE, filename_ext
      File.open(filename, 'wb') do |f|
        f.write(data.read)
      end
    end
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_filter :login_required

  # GET /documents
  def index
    if session[:user][:access] == "manager"
      @documents = Document.find_all_by_organization_id(session[:user][:organization_id], :order => "customer_id asc, horse_id asc, description asc")
    elsif session[:user][:access] == "customer"
      @documents = Document.find_all_by_customer_id(session[:user][:customer_id], :order => "horse_id asc, description asc")
    end
  end

  # GET /documents/1
  def show
    @document = Document.find(params[:id])
    @document.filename = "/files/documents/" + @document.id.to_s + "." + @document.extension
  end

  # GET /documents/new
  def new
    @document = Document.new
    @document.organization_id = session[:user][:organization_id]
    @document.customer_id = params[:customer]
    @document.horse_id = params[:horse]
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  def create
    @document = Document.new(params[:document])
    @image_data = params[:document][:filename]
    @document.extension = @image_data.original_filename.split('.').last
    @document.filename = nil

    if @document.save
      Document.save_image(@document.id, @document.extension, @image_data)
      redirect_to(@document, :notice => 'Document was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /documents/1
  def update
    @document = Document.find(params[:id])

    if @document.update_attributes(params[:document])
      redirect_to(@document, :notice => 'Document was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /documents/1
  def destroy
    @document = Document.find(params[:id])
    @horse = nil
    @customer = nil
    if @document.horse.nil? == false
      @horse = @document.horse
    elsif @document.customer.nil? == false
      @customer = @document.customer
    end
    if @document.destroy
      if @horse.nil? == false && session[:user][:access] != "customer"
        redirect_to(@horse, :notice => 'Document was successfully deleted.')
      elsif @customer.nil? == false && session[:user][:access] != "customer"
        redirect_to(@customer, :notice => 'Document was successfully deleted.')
      else
        redirect_to(documents_path, :notice => 'Document was successfully deleted.')
      end
    end
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document, :html => {:multipart => true}) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :filename %>
    <%= f.file_field :filename %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <%= hidden_field("document", "organization_id",   :value => @document.organization_id) %>
  <%= hidden_field("document", "customer_id",       :value => @document.customer_id) %>
  <%= hidden_field("document", "horse_id",          :value => @document.horse_id) %>
<% end %>

app/views/documents/edit.html.erb
<% if session[:user][:access] == "manager" %>
    <div class="breadcrumb">
      << <%= link_to 'BINDER', documents_path %>
      <% if @document.customer.nil? == false %>
        << <%= link_to @document.customer.last_name.upcase!, @document.customer %>
      <% end %>
      <% if @document.horse.nil? == false %>
        << <%= link_to @document.horse.barn_name.upcase!, @document.horse %>
      <% end %>
      << <%= link_to 'DETAILS', @document %>
    </div>
<% end %>

<div class="list">

<h1 class="title"><%= @document.description %></h1>

<p class="notice"><%= notice %></p>

<%= render 'form' %>

</div>

app/views/documents/index.html.erb
<div class="list">

<h1 class="title">Binder</h1>

<p class="notice"><%= notice %></p>

<% if session[:user][:access] == "customer" %>
    <%= link_to 'Add a new document', new_document_path(:customer => session[:user][:customer_id]), :class => "add_link" %>

    <% if @documents.empty? == false %>
        <table class="margin_above">
          <% @documents.each do |document| %>
            <tr>
              <td><%= link_to document.description, document %></td>
              <% if document.horse.nil? == false %>
                <td><%= document.horse.barn_name %></td>
              <% end %>
              <td><%= link_to 'Edit', edit_document_path(document) %></td>
              <td><a href="#" onclick="confirm('Are you sure you want to delete this document?', '<%= delete_document_path(document) %>')">Remove</a></td>
            </tr>
          <% end %>
        </table>
    <% else %>
        <p class="currently_no">There are currently no documents in your binder.</p>
    <% end %>
<% else %>
    <% if session[:user][:organization_id] %>
        <%= link_to 'Add a new document', new_document_path, :class => "add_link" %>

        <% if @documents.empty? == false %>
            <table class="margin_above">
                <% @documents.each do |document| %>
                  <tr>
                    <td><%= link_to document.description, document %></td>
                    <% if document.customer.nil? == false %>
                        <td><%= document.customer.last_name %>, <%= document.customer.first_name %></td>
                    <% else %>
                        <td>No customer</td>
                    <% end %>
                    <% if document.horse.nil? == false %>
                        <td><%= document.horse.barn_name %></td>
                    <% else %>
                        <td>No horse</td>
                    <% end %>
                    <td><%= link_to 'Edit', edit_document_path(document) %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this document?', '<%= delete_document_path(document) %>')">Remove</a></td>
                  </tr>
                <% end %>
            </table>
        <% else %>
            <p class="currently_no">There are currently no documents in your binder.</p>
        <% end %>
    <% else %>
        <p class="currently_no">You can't start adding documents until you get your barn information entered. <%= link_to 'Click here', new_organization_path %> to do that now.</p>
    <% end %>
<% end %>

</div>

app/views/documents/new.html.erb
<div class="breadcrumb">
  << <%= link_to 'BINDER', documents_path %>
  <% if @document.customer.nil? == false %>
    << <%= link_to @document.customer.last_name.upcase!, @document.customer %>
  <% end %>
  <% if @document.horse.nil? == false %>
    << <%= link_to @document.horse.barn_name.upcase!, @document.horse %>
  <% end %>
</div>

<div class="list">

<h1 class="title">Binder</h1>

<p class="notice"><%= notice %></p>

<%= render 'form' %>

</div>

app/views/documents/show.html.erb
<% if session[:user][:access] == "manager" %>
    <div class="breadcrumb">
      << <%= link_to "BINDER", documents_path %>
      <% if @document.customer.nil? == false %>
        << <%= link_to @document.customer.last_name.upcase, @document.customer %>
      <% end %>
      <% if @document.horse.nil? == false %>
        << <%= link_to @document.horse.barn_name.upcase, @document.horse %>
      <% end %>
    </div>
<% end %>

<div class="list">

<h1 class="title"><%= @document.description %></h1>

<p id="notice"><%= notice %></p>

<div class="field">
    <label>Notes</label>
    <% if @document.notes.blank? == false %>
        <%= @document.notes %>
    <% else %>
        This document does not have any notes.
    <% end %>
</div>

<% if session[:user][:access] == "manager" %>
    <% if @document.customer.nil? == false %>
    <div class="field">
        <label>Customer</label>
        <%= link_to @document.customer.first_name + " " + @document.customer.last_name, @document.customer %>
    </div>
    <% end %>
<% end %>

<% if @document.horse.nil? == false %>
<div class="field">
    <label>Horse</label>
    <% if @document.horse.reg_name.blank? == false %>
        <%= link_to @document.horse.reg_name + " (" + @document.horse.barn_name + ")", horse_path(@document.horse) %>
    <% else %>
        <%= link_to @document.horse.barn_name, horse_path(@document.horse) %>
    <% end %>
</div>
<% end %>

<div id="document_image">

    <% if @document.extension == "pdf" %>
        <iframe src="<%= @document.filename %>" height="1000px" width="900px"></iframe>
    <% else %>
        <img src="<%= @document.filename %>" />
    <% end %>

</div>

</div>