config/routes.rb
EkBilling::Application.routes.draw do

  root :to => 'pages#splash'
  match '/about',                   :to => 'pages#about'
  match '/builder',                 :to => 'pages#builder'
  match '/contact',                 :to => 'pages#contact'
  match '/home',                    :to => 'pages#home'

  match '/login'                    => 'users#login',                   :as => :login
  match '/logout'                   => 'users#logout',                  :as => :logout

  match 'pages/signup'              => 'pages#signup',                  :as => :signup
  match 'pages/access_denied'       => 'pages#access_denied',           :as => :access_denied

  match 'invoices/confirm/:id'      => "invoices#confirm",              :as => :invoice_confirm
  match 'invoices/request_mail/:id' => "invoices#request_mail",         :as => :invoice_request
  match 'invoices/issued/:id'       => "invoices#issued",               :as => :invoice_issued
  match 'invoices/text/:id'         => "invoices#text",                 :as => :invoice_text
  match 'invoices/mailed/:id'       => "invoices#mailed",               :as => :invoice_mailed
  match 'invoices/reminder/:id'     => "invoices#reminder",             :as => :invoice_reminder
  match 'invoices/paid/:id'         => "invoices#paid",                 :as => :invoice_paid

  match 'autos/destroy/:id'         => "autos#destroy",                 :as => :delete_auto
  match 'categories/destroy/:id'    => "categories#destroy",            :as => :delete_category
  match 'customers/destroy/:id'     => "customers#destroy",             :as => :delete_customer
  match 'documents/destroy/:id'     => "documents#destroy",             :as => :delete_document
  match 'horses/destroy/:id'        => "horses#destroy",                :as => :delete_horse
  match 'invoices/destroy/:id'      => "invoices#destroy",              :as => :delete_invoice
  match 'items/destroy/:id'         => "items#destroy",                 :as => :delete_item
  match 'organizations/destroy/:id' => "organizations#destroy",         :as => :delete_organization
  match 'payments/destroy/:id'      => "payments#destroy",              :as => :delete_payment
  match 'users/destroy/:id'         => "users#destroy",                 :as => :delete_user

  match 'customs/sample'            => "customs#sample",                :as => :invoice_sample

  match 'users/create_customer'     => "users#customer_acct_from_form", :as => :customer_from_form
  match 'users/create_manager'      => "users#manager_acct_from_form",  :as => :manager_from_form
  match 'users/new_customer/:id'    => "users#create_customer_account", :as => :new_customer_account
  match 'customers/validate/:id'    => "customers#validate_customer",   :as => :validate_customer
  match 'customers/update'          => "customers#update_info",         :as => :update_customer

  match 'payments/authorize/:id'    => "payments#authorize",            :as => :authorize
  match 'payments/creditcard/:id'   => "payments#creditcard",           :as => :creditcard
  match 'payments/relay_response'   => "payments#relay_response",       :as => :relay_response
  match 'payments/receipt/:id'      => "payments#receipt",              :as => :payment_receipt
  match 'payments/error'            => "payments#error",                :as => :payment_error

  match 'android/getAllCustomers', :to => "android#get_all_customers"

  resources :autos
  resources :categories
  resources :customers
  resources :customs
  resources :documents
  resources :horses
  resources :invoices
  resources :items
  resources :organizations
  resources :payments
  resources :users

end

app/models/organization.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "is not a valid email address") unless
      value =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  end
end

class UrlValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "is not a valid website address") unless
      value =~ /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
  end
end

class Organization < ActiveRecord::Base

  has_many  :users
  has_many  :customers
  has_one   :custom
  has_many  :horses
  has_many  :invoices

  validates :name,      :presence => true, :length => { :maximum => 250 }
  validates :address,   :presence => true, :length => { :maximum => 250 }
  validates :city,      :presence => true, :length => { :maximum => 250 }
  validates :state,     :presence => true, :length => { :maximum => 2 }
  validates :zip,       :presence => true, :length => { :maximum => 10 }
  validates :phone,     :presence => true, :length => { :minimum => 10, :maximum => 25 }, :format => { :with => /\A\S[0-9\+\/\(\)\s\-]*\z/i }
  validates :email,     :email => true, :length => { :maximum => 250 }, :if => :email?
  validates :website,   :url => true, :length => { :maximum => 250 }, :if => :website?
  validates :contact,   :presence => true, :length => { :maximum => 250 }

  def email?()
    if self.email.blank? == false
      true
    end
    false
  end

  def website?()
    if self.website.blank? == false
      true
    end
    false
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_filter :login_required
  before_filter :admin_required, :except => [ :new, :create, :edit, :update ]
  before_filter :manager_required

  # GET /organizations
  def index
    @organizations = Organization.all(:order => "name asc")
  end

  # GET /organizations/1
  def show
    @organization = Organization.find(params[:id])
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  def create
    @organization = Organization.new(params[:organization])

    if @organization.save
      @user = User.find(session[:user])
      @user.update_attribute("organization_id", @organization.id)
      session[:user] = @user
      if session[:user][:access] == "admin"
        redirect_to(@organization, :notice => 'Organization was successfully created.')
      else
        redirect_to(edit_organization_path(@organization), :notice => 'Thanks! Your barn details were successfully updated.')
      end
    else
      render :action => "new"
    end
  end

  # PUT /organizations/1
  def update
    @organization = Organization.find(params[:id])

    if @organization.update_attributes(params[:organization])
      if session[:user][:access] == "admin"
        redirect_to(@organization, :notice => 'Organization was successfully updated.')
      else
        redirect_to(edit_organization_path(@organization), :notice => 'Your barn details were successfully updated.')
      end
    else
      render :action => "edit"
    end
  end

  # DELETE /organizations/1
  def destroy
    @organization = Organization.find(params[:id])
    if @organization.destroy
      redirect_to(organizations_url, :notice => 'Organization was successfully deleted.')
    end
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Barn name</label>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <label>Mailing address</label>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <label>City</label>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <label>State</label>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <label>Zip</label>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <label>Phone</label>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <label>Email</label>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <label>Website</label>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <label>Contact person</label>
    <%= f.text_field :contact %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<% if session[:user][:access] == "admin" %>
    <div class="breadcrumb">
      << <%= link_to 'ORGANIZATIONS', organizations_path %>
      << <%= link_to 'DETAILS', @organization %>
    </div>
<% end %>

<div class="list">

<% if session[:user][:admin] == "admin" %>
    <h1 class="title"><%= @organization.name %></h1>
<% else %>
    <h1 class="title">Your Barn</h1>
    <% if @organization.custom.nil? == false %>
        <%= link_to 'Customize your invoices', edit_custom_path(@organization.custom), :class => "add_link" %>
    <% else %>
        <%= link_to 'Customize your invoices', new_custom_path, :class => "add_link" %>
    <% end %>
<% end %>

<p id="notice" style="margin-top: 20px"><%= notice %></p>

<%= render 'form' %>

</div>

app/views/organizations/index.html.erb
<div class="list">

<h1 class="title">Organizations</h1>

<%= link_to 'Add a new organization', new_organization_path, :class => "add_link" %>

<% if @organizations.empty? == false %>
    <table class="margin_above">
        <% @organizations.each do |organization| %>
          <tr>
            <td><%= link_to organization.name, organization %></td>
            <td><%= organization.contact %></td>
            <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
            <td><a href="#" onclick="confirm('Are you sure you want to delete this organization?', '<%= delete_organization_path(organization) %>')">Remove</a></td>
          </tr>
        <% end %>
    </table>
<% else %>
    <p class="currently_no">There are currently no organizations.</p>
<% end %>

</div>

app/views/organizations/new.html.erb
<% if session[:user][:access] == "admin" %>
    <div class="breadcrumb">
      << <%= link_to 'ORGANIZATIONS', organizations_path %>
    </div>
<% end %>

<div class="list">

<% if session[:user][:admin] == "admin" %>
    <h1 class="title"><%= @organization.name %></h1>
<% else %>
    <h1 class="title">Your Barn</h1>
<% end %>

<%= render 'form' %>

</div>

app/views/organizations/show.html.erb
<% if session[:user][:access] == "admin" %>
    <div class="breadcrumb">
      << <%= link_to 'ORGANIZATIONS', organizations_path %>
    </div>
<% end %>

<div class="list">

<h1 class="title"><%= @organization.name %></h1>

<%= @organization.contact %>
<br />
<%= @organization.address %>
<br />
<%= @organization.city %>, <%= @organization.state %> <%= @organization.zip %>
<br />
<%= number_to_phone(@organization.phone) %>
<br />
<%= link_to @organization.email, "mailto:" + @organization.email %>
<br />
<%= link_to @organization.website, @organization.website %>

  <div class="sub">
    <h2 class="sub_title">Users</h2>
    <%= link_to 'Add a new user', new_user_path(:organization => @organization.id), :class => "add_link" %>
    <% if @organization.users.empty? == false %>
        <table class="margin_above">
            <% @organization.users.each do |user| %>
                <tr>
                    <td><%= user.name %></td>
                    <td><a href="#" onclick="confirm('Are you sure you want to delete this user?', '<%= delete_user_path(user) %>')">REMOVE</a></td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <p class="currently_no">There are currently no users for this organization.</p>
    <% end %>
  </div>

</div>