config/routes.rb
EkBilling::Application.routes.draw do

  root :to => 'pages#splash'
  match '/about',                   :to => 'pages#about'
  match '/builder',                 :to => 'pages#builder'
  match '/contact',                 :to => 'pages#contact'
  match '/home',                    :to => 'pages#home'

  match '/login'                    => 'users#login',                   :as => :login
  match '/logout'                   => 'users#logout',                  :as => :logout

  match 'pages/signup'              => 'pages#signup',                  :as => :signup
  match 'pages/access_denied'       => 'pages#access_denied',           :as => :access_denied

  match 'invoices/confirm/:id'      => "invoices#confirm",              :as => :invoice_confirm
  match 'invoices/request_mail/:id' => "invoices#request_mail",         :as => :invoice_request
  match 'invoices/issued/:id'       => "invoices#issued",               :as => :invoice_issued
  match 'invoices/text/:id'         => "invoices#text",                 :as => :invoice_text
  match 'invoices/mailed/:id'       => "invoices#mailed",               :as => :invoice_mailed
  match 'invoices/reminder/:id'     => "invoices#reminder",             :as => :invoice_reminder
  match 'invoices/paid/:id'         => "invoices#paid",                 :as => :invoice_paid

  match 'autos/destroy/:id'         => "autos#destroy",                 :as => :delete_auto
  match 'categories/destroy/:id'    => "categories#destroy",            :as => :delete_category
  match 'customers/destroy/:id'     => "customers#destroy",             :as => :delete_customer
  match 'documents/destroy/:id'     => "documents#destroy",             :as => :delete_document
  match 'horses/destroy/:id'        => "horses#destroy",                :as => :delete_horse
  match 'invoices/destroy/:id'      => "invoices#destroy",              :as => :delete_invoice
  match 'items/destroy/:id'         => "items#destroy",                 :as => :delete_item
  match 'organizations/destroy/:id' => "organizations#destroy",         :as => :delete_organization
  match 'payments/destroy/:id'      => "payments#destroy",              :as => :delete_payment
  match 'users/destroy/:id'         => "users#destroy",                 :as => :delete_user

  match 'customs/sample'            => "customs#sample",                :as => :invoice_sample

  match 'users/create_customer'     => "users#customer_acct_from_form", :as => :customer_from_form
  match 'users/create_manager'      => "users#manager_acct_from_form",  :as => :manager_from_form
  match 'users/new_customer/:id'    => "users#create_customer_account", :as => :new_customer_account
  match 'customers/validate/:id'    => "customers#validate_customer",   :as => :validate_customer
  match 'customers/update'          => "customers#update_info",         :as => :update_customer

  match 'payments/authorize/:id'    => "payments#authorize",            :as => :authorize
  match 'payments/creditcard/:id'   => "payments#creditcard",           :as => :creditcard
  match 'payments/relay_response'   => "payments#relay_response",       :as => :relay_response
  match 'payments/receipt/:id'      => "payments#receipt",              :as => :payment_receipt
  match 'payments/error'            => "payments#error",                :as => :payment_error

  match 'android/getAllCustomers', :to => "android#get_all_customers"

  resources :autos
  resources :categories
  resources :customers
  resources :customs
  resources :documents
  resources :horses
  resources :invoices
  resources :items
  resources :organizations
  resources :payments
  resources :users

end

app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :organization

  has_many :autos

  validates :category,        :presence => true, :length => { :maximum => 250 }
  validates :name,            :presence => true, :length => { :maximum => 250 }
  validates :amount,          :format => { :with => /^[0-9]*(\.[0-9]{1,2})?$|^[0-9]{1,3}(,[0-9]{3})*(\.[0-9]{1,2})?$/ }, :if => :amount?
  validates :organization_id, :presence => true, :numericality => true

  def amount?()
    if self.amount.blank? == false
      true
    else
      false
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :login_required
  before_filter :manager_required

  def index
    @categories = Category.find_all_by_organization_id(session[:user][:organization_id],
                                                       :order => "category ASC, name ASC")
  end

  # GET /categories/new
  def new
    @category = Category.new
    @category.organization_id = session[:user][:organization_id]
    @types = [ "Farm Expenses", "Show Expenses", "Other Expenses" ]
  end

  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @types = [ "Farm Expenses", "Show Expenses", "Other Expenses" ]
  end

  # POST /payments
  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to(@category, :notice => 'Category was successfully created.')
    else
      format.html { render :action => "new" }
    end
  end

  # PUT /categories/1
  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to(@category, :notice => 'Category was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /categories/1
  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to(categories_url)
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %>
    <%= select("category", "category", @types.collect { |p| [p, p] }) %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <%= hidden_field("category", "organization_id", :value => @category.organization_id)  %>
<% end %>

app/views/categories/edit.html.erb
<div class="breadcrumb">
  << <%= link_to 'CATEGORIES', categories_path %>
  << <%= link_to 'DETAILS', @category %>
</div>

<div class="list">

<h1 class="title"><%= @category.name %></h1>

<p class="notice"><%= notice %></p>

<%= render 'form' %>

</div>

app/views/categories/index.html.erb
<div class="list">

<h1 class="title">Categories</h1>

<p class="notice"><%= notice %></p>

<% if session[:user][:organization_id] %>
    <%= link_to 'Add a new category', new_category_path, :class => "add_link" %>

    <% if @categories.empty? == false %>
        <table class="margin_above">
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.category %> - <%= category.name %></td>
                <td><%= number_to_currency(category.amount) %></td>
                <td><%= link_to 'Edit', edit_category_path(category) %></td>
                <td><a href="#" onclick="confirm('Are you sure you want to delete this category?', '<%= delete_category_path(category) %>')">Remove</a></td>
              </tr>
            <% end %>
        </table>
    <% else %>
        <p class="currently_no">There are currently no categories.</p>
    <% end %>
<% else %>
    <p class="currently_no">You can't start adding categories until you get your barn information entered. <%= link_to 'Click here', new_organization_path %> to do that now.</p>
<% end %>

</div>

app/views/categories/new.html.erb
<div class="breadcrumb">
  << <%= link_to 'CATEGORIES', categories_path %>
</div>

<div class="list">

<h1 class="title">CATEGORIES</h1>

<p class="notice"><%= notice %></p>

<%= render 'form' %>

</div>

app/views/categories/show.html.erb
<div class="breadcrumb">
  << <%= link_to 'CATEGORIES', categories_path %>
</div>

<div class="list">

<h1 class="title"><%= @category.name %></h1>

<p id="notice"><%= notice %></p>

<div class="field">
  <label>Category</label>
  <%= @category.category %>
</div>

<div class="field">
  <label>Name</label>
  <%= @category.name %>
</div>

<div class="field">
  <label>Amount</label>
  <%= number_to_currency(@category.amount) %>
</div>

<%= link_to 'Edit details', edit_category_path(@category), :class => "link_button" %>
<a href="#" onclick="confirm('Are you sure you want to delete this category?', '<%= delete_category_path(@category) %>')" class="link_button">Remove</a>

</div>